### ISSUE TITLE
作者大大您好，我想要再造一遍差不多的轮子，请问应该怎么做？

### ISSUE THREAD

**Issue by Mintpix** [wzyy2/PiBox#2]
嗯..我是一个python初学者，对javascript一点都不懂，现在知道了用django可以快速搭一个项目后脑海里出现的想法与您的不谋而合。我的主要目的是为了学习夯实一些基础。所以想知道除了django之外还有什么要补充的知识吗（js/html/css这些已经知道了）？

**Comment by wzyy2** [comment]
直接写呀

**Comment by Mintpix** [comment]
嗯！
